FETCH_USER_INFO_NODE = "fetch_user_info_node"
PRIMARY_ASSISTANT = "primary_assistant"
PRIMARY_ASSISTANT_TOOLS_NODE = "primary_assistant_tools_node"

TAXI_ENTRY_NODE = "taxi_entry_node"
TAXI_ASSISTANT = "taxi_assistant"
TAXI_ASSISTANT_TOOL_HANDLER = "taxi_assistant_tool_handler"
TAXI_ASSISTANT_RETURN_NODE = "taxi_assistant_return_node"
TAXI_ASSISTANT_SENSITIVE_TOOLS = "taxi_assistant_sensitive_tools"
TAXI_ASSISTANT_SAFE_TOOLS = "taxi_assistant_safe_tools"